name: Masar Academy 2015
favicon: null
layout_spectrum: 0.74625
typography_spectrum: 0.10393348382785916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#17365d'
    - '#1a70a8'
    - '#c69888'
    - '#766020'
  brandStrength: 0.75
  lightness: 0.04333650344051421
  saturation: 0.08017687872052193
  rhythmicContrast: 0.6738069003913552
purpose: []
